title: Morgan Potter
subtitle: Just a blog
baseurl: ""
url: "https://morgan-potter.github.io"
author:
  name: Morgan Potter
  avatar: "/assets/author.jpg"
  bio: Hi, my name is Morgan Potter. I am a year 12 student currently studying at Burgmann Anglican School. I created this website as a weekly log of projects, challenges, ideas and self-reflection as my learning in IT continues through college.
  location: ACT, Australia
  links:
    - label: 'GitHub'
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Morgan-Potter"
    - label: 'LinkedIn'
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/morgan-potter-740481252/"
    - label: 'Email'
      icon: "fas fa-fw fa-envelope"
      url: "mailto:morganpotter005@gmail.com"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
minimal_mistakes_skin: "dark"

include:
  - _pages
  - _include

search: true

google_verify: AF5ROVNCfawrGrUydEUq6YUhsGvaunvutUtuytPEwpE

mathjax: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      classes: wide
      excerpt: ""
      header:
        overlay_image: "/assets/default-image.jpg"
        overlay_color: "#000"
        overlay_filter: "0.5"
